kind = "web"
previewPath = "/"
title = "UN-VC"
version = "1.0.0"
id = "artifacts/un-vc"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25693

[services.development]
run = "pnpm --filter @workspace/un-vc run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/un-vc", "run", "build" ]
publicDir = "artifacts/un-vc/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25693"
BASE_PATH = "/"
